// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meta.sql

package sqlitedb

import (
	"context"
)

const deleteMeta = `-- name: DeleteMeta :exec
DELETE FROM kv WHERE key = ?
`

func (q *Queries) DeleteMeta(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteMeta, key)
	return err
}

const getMeta = `-- name: GetMeta :one
SELECT value FROM kv WHERE key = ? LIMIT 1
`

func (q *Queries) GetMeta(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMeta, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listMeta = `-- name: ListMeta :many
SELECT key, value FROM kv ORDER BY key
`

func (q *Queries) ListMeta(ctx context.Context) ([]Kv, error) {
	rows, err := q.db.QueryContext(ctx, listMeta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Kv{}
	for rows.Next() {
		var i Kv
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMeta = `-- name: SetMeta :exec
INSERT INTO kv (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetMetaParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetMeta(ctx context.Context, arg SetMetaParams) error {
	_, err := q.db.ExecContext(ctx, setMeta, arg.Key, arg.Value)
	return err
}
