// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

import (
	"database/sql"
)

type Kv struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type PinChallenge struct {
	ID        int64  `json:"id"`
	UserID    int64  `json:"user_id"`
	PinHash   string `json:"pin_hash"`
	ExpiresAt int64  `json:"expires_at"`
	CreatedAt int64  `json:"created_at"`
}

type RecoveryToken struct {
	ID        int64  `json:"id"`
	UserID    int64  `json:"user_id"`
	TokenHash string `json:"token_hash"`
	ExpiresAt int64  `json:"expires_at"`
}

type User struct {
	ID             int64          `json:"id"`
	Email          string         `json:"email"`
	Name           string         `json:"name"`
	PassHash       string         `json:"pass_hash"`
	Role           string         `json:"role"`
	ClientName     sql.NullString `json:"client_name"`
	TelegramChatID sql.NullString `json:"telegram_chat_id"`
	TelegramBind   sql.NullString `json:"telegram_bind"`
	Theme          string         `json:"theme"`
	MapStyle       string         `json:"map_style"`
	Disabled       int64          `json:"disabled"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}
