// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pins.sql

package sqlitedb

import (
	"context"
)

const deleteExpiredPinChallenges = `-- name: DeleteExpiredPinChallenges :exec
DELETE FROM pin_challenges WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredPinChallenges(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPinChallenges, expiresAt)
	return err
}

const deletePinChallenges = `-- name: DeletePinChallenges :exec
DELETE FROM pin_challenges WHERE user_id = ?
`

func (q *Queries) DeletePinChallenges(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deletePinChallenges, userID)
	return err
}

const getPinChallenge = `-- name: GetPinChallenge :one
SELECT id, user_id, pin_hash, expires_at, created_at
FROM pin_challenges WHERE user_id = ? ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetPinChallenge(ctx context.Context, userID int64) (PinChallenge, error) {
	row := q.db.QueryRowContext(ctx, getPinChallenge, userID)
	var i PinChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PinHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertPinChallenge = `-- name: InsertPinChallenge :exec
INSERT INTO pin_challenges (user_id, pin_hash, expires_at, created_at)
VALUES (?, ?, ?, ?)
`

type InsertPinChallengeParams struct {
	UserID    int64  `json:"user_id"`
	PinHash   string `json:"pin_hash"`
	ExpiresAt int64  `json:"expires_at"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) InsertPinChallenge(ctx context.Context, arg InsertPinChallengeParams) error {
	_, err := q.db.ExecContext(ctx, insertPinChallenge,
		arg.UserID,
		arg.PinHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}
