// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recovery.sql

package sqlitedb

import (
	"context"
)

const deleteExpiredRecoveryTokens = `-- name: DeleteExpiredRecoveryTokens :exec
DELETE FROM recovery_tokens WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredRecoveryTokens(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredRecoveryTokens, expiresAt)
	return err
}

const deleteRecoveryToken = `-- name: DeleteRecoveryToken :exec
DELETE FROM recovery_tokens WHERE id = ?
`

func (q *Queries) DeleteRecoveryToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecoveryToken, id)
	return err
}

const deleteRecoveryTokensForUser = `-- name: DeleteRecoveryTokensForUser :exec
DELETE FROM recovery_tokens WHERE user_id = ?
`

func (q *Queries) DeleteRecoveryTokensForUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecoveryTokensForUser, userID)
	return err
}

const getRecoveryToken = `-- name: GetRecoveryToken :one
SELECT id, user_id, token_hash, expires_at
FROM recovery_tokens WHERE token_hash = ? LIMIT 1
`

func (q *Queries) GetRecoveryToken(ctx context.Context, tokenHash string) (RecoveryToken, error) {
	row := q.db.QueryRowContext(ctx, getRecoveryToken, tokenHash)
	var i RecoveryToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
	)
	return i, err
}

const insertRecoveryToken = `-- name: InsertRecoveryToken :exec
INSERT INTO recovery_tokens (user_id, token_hash, expires_at)
VALUES (?, ?, ?)
`

type InsertRecoveryTokenParams struct {
	UserID    int64  `json:"user_id"`
	TokenHash string `json:"token_hash"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) InsertRecoveryToken(ctx context.Context, arg InsertRecoveryTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertRecoveryToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}
