// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByClientName = `-- name: GetUserByClientName :one
SELECT id, email, name, pass_hash, role, client_name, telegram_chat_id, telegram_bind, theme, map_style, disabled, created_at, updated_at
FROM users WHERE client_name = ? LIMIT 1
`

func (q *Queries) GetUserByClientName(ctx context.Context, clientName sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByClientName, clientName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PassHash,
		&i.Role,
		&i.ClientName,
		&i.TelegramChatID,
		&i.TelegramBind,
		&i.Theme,
		&i.MapStyle,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, pass_hash, role, client_name, telegram_chat_id, telegram_bind, theme, map_style, disabled, created_at, updated_at
FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PassHash,
		&i.Role,
		&i.ClientName,
		&i.TelegramChatID,
		&i.TelegramBind,
		&i.Theme,
		&i.MapStyle,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, pass_hash, role, client_name, telegram_chat_id, telegram_bind, theme, map_style, disabled, created_at, updated_at
FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PassHash,
		&i.Role,
		&i.ClientName,
		&i.TelegramChatID,
		&i.TelegramBind,
		&i.Theme,
		&i.MapStyle,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByTelegramBind = `-- name: GetUserByTelegramBind :one
SELECT id, email, name, pass_hash, role, client_name, telegram_chat_id, telegram_bind, theme, map_style, disabled, created_at, updated_at
FROM users WHERE telegram_bind = ? AND telegram_bind IS NOT NULL AND telegram_bind != '' LIMIT 1
`

func (q *Queries) GetUserByTelegramBind(ctx context.Context, telegramBind sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByTelegramBind, telegramBind)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PassHash,
		&i.Role,
		&i.ClientName,
		&i.TelegramChatID,
		&i.TelegramBind,
		&i.Theme,
		&i.MapStyle,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByTelegramChatID = `-- name: GetUserByTelegramChatID :one
SELECT id, email, name, pass_hash, role, client_name, telegram_chat_id, telegram_bind, theme, map_style, disabled, created_at, updated_at
FROM users WHERE telegram_chat_id = ? LIMIT 1
`

func (q *Queries) GetUserByTelegramChatID(ctx context.Context, telegramChatID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByTelegramChatID, telegramChatID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PassHash,
		&i.Role,
		&i.ClientName,
		&i.TelegramChatID,
		&i.TelegramBind,
		&i.Theme,
		&i.MapStyle,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :execresult
INSERT INTO users (
  email, name, pass_hash, role, client_name, telegram_chat_id, telegram_bind,
  theme, map_style, disabled, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertUserParams struct {
	Email          sql.NullString `json:"email"`
	Name           string         `json:"name"`
	PassHash       string         `json:"pass_hash"`
	Role           string         `json:"role"`
	ClientName     sql.NullString `json:"client_name"`
	TelegramChatID sql.NullString `json:"telegram_chat_id"`
	TelegramBind   sql.NullString `json:"telegram_bind"`
	Theme          string         `json:"theme"`
	MapStyle       string         `json:"map_style"`
	Disabled       int64          `json:"disabled"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertUser,
		arg.Email,
		arg.Name,
		arg.PassHash,
		arg.Role,
		arg.ClientName,
		arg.TelegramChatID,
		arg.TelegramBind,
		arg.Theme,
		arg.MapStyle,
		arg.Disabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, pass_hash, role, client_name, telegram_chat_id, telegram_bind, theme, map_style, disabled, created_at, updated_at
FROM users ORDER BY CASE role WHEN 'root' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END, email
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PassHash,
			&i.Role,
			&i.ClientName,
			&i.TelegramChatID,
			&i.TelegramBind,
			&i.Theme,
			&i.MapStyle,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET
  email = ?,
  name = ?,
  pass_hash = ?,
  role = ?,
  client_name = ?,
  telegram_chat_id = ?,
  telegram_bind = ?,
  theme = ?,
  map_style = ?,
  disabled = ?,
  updated_at = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Email          sql.NullString `json:"email"`
	Name           string         `json:"name"`
	PassHash       string         `json:"pass_hash"`
	Role           string         `json:"role"`
	ClientName     sql.NullString `json:"client_name"`
	TelegramChatID sql.NullString `json:"telegram_chat_id"`
	TelegramBind   sql.NullString `json:"telegram_bind"`
	Theme          string         `json:"theme"`
	MapStyle       string         `json:"map_style"`
	Disabled       int64          `json:"disabled"`
	UpdatedAt      string         `json:"updated_at"`
	ID             int64          `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Email,
		arg.Name,
		arg.PassHash,
		arg.Role,
		arg.ClientName,
		arg.TelegramChatID,
		arg.TelegramBind,
		arg.Theme,
		arg.MapStyle,
		arg.Disabled,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
